In [30]:
import time


def process(n):
    left = np.ones(3) * n
    right = np.ones(3) * (-n)
    middle = np.zeros(3)
    return left, middle, right


total = 0
N = 5

start = time.time()
for n in range(N):
    print(process(n))
elapsed_time = time.time() - start

print(total)
print('elapsed: {:.5f} [sec]'.format(elapsed_time))

(array([ 0.,  0.,  0.]), array([ 0.,  0.,  0.]), array([ 0.,  0.,  0.]))
(array([ 1.,  1.,  1.]), array([ 0.,  0.,  0.]), array([-1., -1., -1.]))
(array([ 2.,  2.,  2.]), array([ 0.,  0.,  0.]), array([-2., -2., -2.]))
(array([ 3.,  3.,  3.]), array([ 0.,  0.,  0.]), array([-3., -3., -3.]))
(array([ 4.,  4.,  4.]), array([ 0.,  0.,  0.]), array([-4., -4., -4.]))
0
elapsed: 0.00292 [sec]


In [31]:
from joblib import Parallel, delayed


N = 10

start = time.time()
r = Parallel(n_jobs=-1)([delayed(process)(n) for n in range(N)])
elapsed_time = time.time() - start

print(type(r))
r = np.array(r)
print(r.shape)
print(r)
print('elapsed: {:.5f} [sec]'.format(elapsed_time))

<class 'list'>
(10, 3, 3)
[[[ 0.  0.  0.]
  [ 0.  0.  0.]
  [ 0.  0.  0.]]

 [[ 1.  1.  1.]
  [ 0.  0.  0.]
  [-1. -1. -1.]]

 [[ 2.  2.  2.]
  [ 0.  0.  0.]
  [-2. -2. -2.]]

 [[ 3.  3.  3.]
  [ 0.  0.  0.]
  [-3. -3. -3.]]

 [[ 4.  4.  4.]
  [ 0.  0.  0.]
  [-4. -4. -4.]]

 [[ 5.  5.  5.]
  [ 0.  0.  0.]
  [-5. -5. -5.]]

 [[ 6.  6.  6.]
  [ 0.  0.  0.]
  [-6. -6. -6.]]

 [[ 7.  7.  7.]
  [ 0.  0.  0.]
  [-7. -7. -7.]]

 [[ 8.  8.  8.]
  [ 0.  0.  0.]
  [-8. -8. -8.]]

 [[ 9.  9.  9.]
  [ 0.  0.  0.]
  [-9. -9. -9.]]]
elapsed: 0.18553 [sec]


In [3]:
n_docs = 10
n_features = 7
n_topics = 5

phi = np.ones((n_docs, n_features, n_topics))
print(phi.sum(axis=0).T.shape)

(5, 7)


In [5]:
from scipy.stats import dirichlet

alpha = np.arange(5) + 1

alphas = [[1, 2, 3, 4, 5],
         [6, 7, 8, 9, 10]]

print(alpha)
for alpha in alphas:
    rvs = dirichlet.rvs(alpha=alpha, size=1)
    print(rvs)

phi_d = np.ones((n_features, n_topics)) / n_topics
print(phi_d)

print(phi_d[2])
print(phi_d[2, :])

[1 2 3 4 5]
[[ 0.05926371  0.09343999  0.36687486  0.12448064  0.35594081]]
[[ 0.18909163  0.22127959  0.1241978   0.17744479  0.28798619]]
[[ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]
 [ 0.2  0.2  0.2  0.2  0.2]]
[ 0.2  0.2  0.2  0.2  0.2]
[ 0.2  0.2  0.2  0.2  0.2]


In [22]:
np.random.mtrand._rand.gamma
np.random.RandomState

mtrand.RandomState

In [28]:
init_gamma = 100.
init_var = 1. / init_gamma
n_components = 5
n_features = 10
r = np.random.RandomState(seed=None)
components = r.gamma(init_gamma,
                                          init_var,
                                          (n_components, n_features))
print(components)
np.random.mtrand._rand

[[ 1.06197871  1.10765762  1.15800937  1.02639692  0.94031248  0.93975469
   0.96316042  0.9094494   0.9420897   1.1459723 ]
 [ 0.968794    0.83549522  1.04755428  0.99411967  0.89974698  1.14443891
   0.97623998  0.97546639  0.89168483  1.31294059]
 [ 0.98193616  0.85292393  1.06726771  0.78914579  0.99673248  1.08449141
   0.93657077  0.91060739  1.04468419  1.02524915]
 [ 0.99923179  0.91846218  0.9812982   0.95022479  0.94032746  0.97047832
   1.15326127  1.12302715  1.03685493  1.10264692]
 [ 0.93123621  1.05035117  1.01170523  0.80622627  0.84694043  0.96743042
   0.97544831  0.88897928  1.02413639  1.14494138]]
